import torch
import numpy as np
import os

def get_global_label_map():
    """
    Since data is already split, we assume labels are 0-33 as generated by the FL data split.
    If a mapping is needed, we can define it here. For CIC-IoT23 FL split, labels are usually 0-33.
    """
    return None

def get_client_data(config, client_id, task_id, global_label_map=None):
    federated_dir = r"c:\FederatedLearning\FL\core\data_split\federated_data"
    # Note: task_id in federated_data is 1-indexed (1 to 6)
    path = os.path.join(federated_dir, f"client_{client_id}_task_{task_id}.pt")
    
    if not os.path.exists(path):
        return None, None
        
    data = torch.load(path, map_location='cpu', weights_only=False)
    x = data['x'].numpy()
    y = data['y'].numpy()
    
    if config.debug:
        limit = min(500, len(x))
        indices = np.random.choice(len(x), limit, replace=False)
        x = x[indices]
        y = y[indices]
        
    if global_label_map is not None:
        y = np.array([global_label_map.get(l, l) for l in y])
        
    return x, y

def get_global_test_data(config, global_label_map=None):
    test_path = r"c:\FederatedLearning\FL\core\data_split\global_test_data.pt"
    if not os.path.exists(test_path):
        raise FileNotFoundError("Global Test Set not found.")
        
    test_data = torch.load(test_path, map_location='cpu', weights_only=False)
    if isinstance(test_data, dict):
        X_test, Y_test = test_data['x'], test_data['y']
    else:
        X_test, Y_test = test_data
        
    X_test = X_test.numpy()
    Y_test = Y_test.numpy()
    
    if global_label_map is not None:
        mask = np.isin(Y_test, list(global_label_map.keys()))
        X_test = X_test[mask]
        Y_test = Y_test[mask]
        Y_test = np.array([global_label_map[l] for l in Y_test])
        
    if config.debug:
        limit = min(2000, len(X_test))
        indices = np.random.choice(len(X_test), limit, replace=False)
        X_test = X_test[indices]
        Y_test = Y_test[indices]
        
    return X_test, Y_test

def oh(y, num_classes):
    return np.eye(num_classes)[y.astype(int)]
